version: '3'
services:
  llm-sre:
    build: 
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    container_name: llm-sre
    ports:
      - 8888:8888
    volumes:
      - ./:/home/ana/llm-sre

volumes:
  llm-sre: